- hosts: all
  gather_facts: false
  tasks:
      - name: update project using git
        git:
          dest: "{{project_path|quote}}"
          repo: "{{scm_url}}"
          version: "{{scm_branch|default(omit)|quote}}"
          force: "{{scm_clean}}"
          bare: "{{bare|default(omit)}}"
          refspec: "{{refspec|default(omit)}}"
          accept_hostkey: "{{scm_accept_hostkey|default(omit)}}"
        register: git_result